@extends('layouts.app')

@section('title', 'Privacy Policy - ppthetraveller Best Tour Packages')
@section('meta_description', 'Get in touch with us for any inquiries about our tour packages')

@section('content')
<div class="container mx-auto p-4 md:p-8">
    <h1 class="text-4xl font-bold mb-8">Privacy Policy</h1>
    <p class="text-lg mb-8">Last updated: May 06, 2024</p>
    <p class="text-lg mb-8">This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
    <h2 class="text-2xl font-bold mb-4">Interpretation and Definitions</h2>
    <p class="text-lg mb-8">The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
    <h2 class="text-2xl font-bold mb-4">Definitions</h2>
    <p class="text-lg mb-8">For the purposes of this Privacy Policy:</p>
    <ul class="list-disc text-lg mb-8">
        <li>Account means a unique account created for You to access our Service or parts of our Service.</li>
        <li>Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
        <li>Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to PP The Traveller.</li>
        <li>Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
        <li>Country refers to: Meghalaya, India</li>
        <li>Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
        <li>Personal Data is any information that relates to an identified or identifiable individual.</li>
        <li>Service refers to the Website.</li>
        <li>Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
        <li>Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
        <li>Website refers to PP The Traveller, accessible from https://www.ppthetraveller.com</li>
    </ul>
    <p class="text-lg mb-8">You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
</div>

@endsection